// Generated by scripts/generate-official-lock.mjs; do not edit.
// Module rationale: generated official-skill lock table is kept
// contiguous so digest/version updates remain mechanical and reviewable.

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) struct OfficialSkillLockEntry {
    pub(crate) skill_id: &'static str,
    pub(crate) version: &'static str,
    pub(crate) digest: &'static str,
}

pub(crate) const OFFICIAL_SKILLS: &[OfficialSkillLockEntry] = &[
    OfficialSkillLockEntry {
        skill_id: "runx/agency",
        version: "sha-eba8afb97ff7",
        digest: "01339546cbb21bcb1d16b371a8942c46e0ee6789f68e470eac7b0e5993d866c7",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/audit-receipt",
        version: "sha-f620d85c5b74",
        digest: "0380dbbc9d3d4787134bc5e92d2e8f3b2d5e86bba3d3ea7a788769ca0eeca961",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/brand-voice",
        version: "sha-554f43f0a0c5",
        digest: "4a1c116664b67eeac12e8490735cba5f7cd0c80cb071b294bb6a3f58b80546e9",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/business-ops",
        version: "sha-d91637d62eed",
        digest: "7801492f5b8fa34f0f6e91f9f2729396744c35fe517ae275885e07204bc52b6f",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/charge",
        version: "sha-8081f8bffc3f",
        digest: "265fb64208b7a553f7b66b0f20f0cd5967f15d2ea76482bff03cb7032d382a8e",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/chief-of-staff",
        version: "sha-29b860639852",
        digest: "9fadb6380a76390dbcbeba0eed904ca568787189653f352404ca7dfb48d09ce9",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/content-pipeline",
        version: "sha-65d48edc3561",
        digest: "59eef5811ad40f220a81e2952f9391a0a23d229e5f533e7f1b4c988863a8efce",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/cve-audit",
        version: "sha-2bf2f887917b",
        digest: "236fdef67d382a54c38b0bf5f1cb96e34ad205baea44bab80aa24619972a2713",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/data-store",
        version: "sha-bbae938bfdbc",
        digest: "b5b508361c4c6db175bfa664418d9a5449f7d40d90938982ce388dd3be154de2",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/deep-research",
        version: "sha-3e179192c25c",
        digest: "c2a3ad055574fe8a601f6b36497756f3b527eefad75a49981b219c916ef15d81",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/dispute-respond",
        version: "sha-67cfecfed4eb",
        digest: "4d510b1517676078f772fc121c4ff0a52e9eb13f049b5103c5bd8664d6fce5e6",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/ecosystem-brief",
        version: "sha-a1d448438c40",
        digest: "e8a138e6c05bb8f51c0012733e43aa6f7756aacb7f4c3c6c67282e4a663b099d",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/extract",
        version: "sha-ed3543746e78",
        digest: "7d0906a46fcf532c7903a3c0645174b7fd15a91682b782173d92b676df6ff7a9",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/ghostwrite",
        version: "sha-2037027913a0",
        digest: "037e4ebc23cdb31bdaa14b498ea705ceb23764efba0904eb743915f1fbf48ef9",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/github-sync",
        version: "sha-921666a0dbbe",
        digest: "a5fb94a3ac3a5dfbb26bfcb897de90f75b010d8642e68cc04f595a4e3bc0685b",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/google-analytics",
        version: "sha-352442341fda",
        digest: "d6c23b6ec788fc4f06711c445ed8faa3121b2705568dcda805d4635cc29a8bd2",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/google-search-console",
        version: "sha-fe1e5dad4e06",
        digest: "58034fe89c3893b58c97cf00a1282283423545ba3c9472312846b1f8db2088a6",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/governed-outbound",
        version: "sha-92150f21abfd",
        digest: "7a35b84dab2cd9b9196ec90390765f0ba93bc85ed6272eee11ef935bc854f9e5",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/helpdesk",
        version: "sha-1a11b3d73eff",
        digest: "d386485916fad9392810d97e814e19c402c9eb6a13637b8a80deb0621c7956d3",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/issue-intake",
        version: "sha-414cec71862a",
        digest: "4b6a78d038e0d0a630e8614a95b212324af8e65a617cbb507ac362151f6faab5",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/issue-to-pr",
        version: "sha-096e8ec4ac27",
        digest: "27a4c8fb5e5f4bf2a2b38763af1316a4297005da01ac7d06af7271a0a6d7b3b5",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/issue-triage",
        version: "sha-d10afa330181",
        digest: "e9d36f92fb325a7341babf206ad2fac2b2734bb686717203709715fdfc3fd9d8",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/knowledge-router",
        version: "sha-4ff91648a69a",
        digest: "e148d7ebf0163c2c1f38b1b55c821e29fb7418c04d361a4e9485e4aca6ef7966",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/lead-enrichment",
        version: "sha-f01ca3c98d43",
        digest: "5e0d371bc8a6bb178d0b355abad9a0bf3ae6046ed199f38fe850ce64c48f27e7",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/lead-router",
        version: "sha-fd8c6d0d594e",
        digest: "f875a05d9e79a2573d3152430093971462f25086ae0518ecee29f0d69e8e3491",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/least-privilege",
        version: "sha-d5517d680c08",
        digest: "b5531e32914f813fbd506672b368040c5cfb64d43b28ae90d1056c7d7aa48986",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/ledger",
        version: "sha-5c8aa65b30fb",
        digest: "9e3370c09616f2ae0490bfacbf9e944a4631f3e9569c71f2d00133ee1c939afe",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/messageboard",
        version: "sha-95655812ff33",
        digest: "5f8a028b7c9105d719befeb413b116e57efa005adb11cf4a743fc41a677406e7",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/mock-charge",
        version: "sha-3c3ad4acd471",
        digest: "40f9cb0afba40701cc11d3f66259207f166d7b58a5a10e058c00b18935d07bec",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/mock-pay",
        version: "sha-ae06409b3d00",
        digest: "d07f071fb2750e549d7509a73400ca1bcb3e3f861c23681990354602b9604d60",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/mock-refund",
        version: "sha-800a44cc324b",
        digest: "d26ecb63db16eb71b50a2e972f5a73b013ff7fd8e9e08842d29056f76f5b0584",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/moltbook",
        version: "sha-14c3b640eaa3",
        digest: "b0c58ee66aeb38ab8a08f0479f6127f72406826c260c4577894a90ace79d5886",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/mpp-charge",
        version: "sha-ceb95af98704",
        digest: "2fde12e2a17a9293bcde4b7b678d32ba52e9cb4acf861f9ad04f6835ce928214",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/mpp-pay",
        version: "sha-3048250032a8",
        digest: "9fb232c26b5d8c5bc94b2fdf2f0e8521b4c6d599fa6fc7e8f2f4ce36eba3d0a0",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/mpp-refund",
        version: "sha-65bb5302b09b",
        digest: "f799a44a9c6f6f893b111472c36e296a6d329bba5e7838db2faa2a40ce7618d4",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/n8n-handoff",
        version: "sha-47029ea0a775",
        digest: "7bf1fa3209cde0f949f2db0d66b28a2ffd6609444b42da62bfce4b2e6a786a5e",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/nitrosend",
        version: "sha-3acd321e3f51",
        digest: "3edfe4b5deb4fcb78beacaf3566e57443945ba5fe002e46aaaf304563aeaf32d",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/nws-weather-forecast",
        version: "sha-737b843fc91c",
        digest: "382cdef84f660e7cfdc2dbbfd7e8382d204d1f4ee46ffa019549615f9c2f745c",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/open-meteo-weather-forecast",
        version: "sha-53a4d630625c",
        digest: "041e0ec18fa4b646b46b72d34662eabbbfbc43ab5a3a65423b49b3e94e81d159",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/operator-inbox",
        version: "sha-11712670454a",
        digest: "368dd1ece62cbab35a597893210ee296af86cc42e1e7c61a0c174177428df05d",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/ops-desk",
        version: "sha-1dcfa3e80a64",
        digest: "61e36b3140f03cb2ec15f423322f936837fd3809ddb53e88c01ee657bd4acb95",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/organic-growth",
        version: "sha-dddc6c32cf25",
        digest: "115d06eb9a646f67f0020ef0bb80abe3a1adfe80b8872f11d161cff39b357683",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/overlay",
        version: "sha-e2c27e300817",
        digest: "1cf147a79735b7e927e9cfa85105c8f9eb40752347491a3142a079de2c707cbd",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/policy-author",
        version: "sha-957d4b38ff5f",
        digest: "9c5da4bc2950eeb8b8b060a920021671272b9232d3c265f878620ffa0d1d6c6c",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/pr-review-note",
        version: "sha-9476f3cf5b2a",
        digest: "7412311ddc40d17d18fd8d35d8d89ee768b1c4ac13c1958bfb5312814ed98d34",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/prior-art",
        version: "sha-797940512288",
        digest: "4aa9584eaa2611908cb2f676b2d81149893f0e0778e974434ab615e95e053c21",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/redact-pii",
        version: "sha-569d972a8748",
        digest: "2358e19a81b07f70bdefee629290d7d132592b8b9f6491abedd44d4bf6837810",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/reflect-digest",
        version: "sha-0f87282e69b3",
        digest: "1b6b29fb22758f05df90233dbb96555c89d061abd1e974e4069c360e74fc4766",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/refund",
        version: "sha-328fb2fe6845",
        digest: "9e655220841617355fdb58dfa7752db2ed1f752b39935a154da2b284121fa7c5",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/release",
        version: "sha-4be1848a2c1b",
        digest: "7d75c52dfe90f1ba1ab916ce0cb050f9e9168441d5359cc7038455ff3161e0b0",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/research",
        version: "sha-a7dcaf105b8f",
        digest: "cec62f7de7f174d5edeb806528b774840511519f89a5d7f917795e4a34b8555e",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/review-receipt",
        version: "sha-16d5691f25f0",
        digest: "df2dff75565f0c2675e8241acbc8cf04fbc64d5aa0cc004fd987c29a75c5136b",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/review-skill",
        version: "sha-cf83dc69577e",
        digest: "f392318b16f97b0877c200edf3529b219fbdb1b1d9350b7a134766f8627b675a",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/run-history",
        version: "sha-0a001ba64fd8",
        digest: "6a87c41e9a7bfb26632be26efbc04de8a7f455de6d766553138505b394e051ce",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/sandbox-harden",
        version: "sha-1dab917c8f86",
        digest: "71d3af2b20b874a39f2b5d9fb199c7edc18192181123cbe3bb3f6cbf4e47db47",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/send-as",
        version: "sha-1f90b9364a3a",
        digest: "cb8959b40115d1090a1f6da7902b3ce5cd6c735adf09fb4e89f25d31ef16e88f",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/settle-invoice",
        version: "sha-12e36842e18f",
        digest: "b224db1ee54d3a64657ab215e4928c2cbc4dbd17a44be5c78cf8c7af2de5019f",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/sign-receipt",
        version: "sha-1651a84c3ef4",
        digest: "512935aa95e2884f7bf8e45b1ba0a8bc071b249f5ed296a81fe767023d0cfae3",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/skill-lab",
        version: "sha-49e3021e0480",
        digest: "dc6acfb5b149b25bb761ae397ae4ccd6c11e33c0c9c21c1c5fb71ee073adcd6a",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/slack",
        version: "sha-c1d2ce22e07e",
        digest: "85c8069a5a738c0241110ac6e01422eb530ee9528eef9dc8ca29a5199672c1c9",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/slack-notify",
        version: "sha-d1bd47a31d9e",
        digest: "92033a99ae1942f34e89e3a3abe7da95cc53fbf2dcb08ac55fcc8c13b1409719",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/sourcey",
        version: "sha-898a86fdded2",
        digest: "c4e7c697e7f4a3fee9f3221a36bc55aefe348755662828e7d97f0cb7d7ad9511",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/spend",
        version: "sha-496870d44d39",
        digest: "f319654d2e4dd18820cf528ad9a614e210f655440f5e12b2a2d70d2ba8c736bd",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/sql-analyst",
        version: "sha-b4860ab0f8cd",
        digest: "460274b826b51d65dc87ff44a575068917b6af53d4e4bc92c00fab8ef2999f84",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/stripe-charge",
        version: "sha-44d8cf2e2949",
        digest: "f511e18de56dbf0360961147049e0bb34d8a527b04681ba53df99a5a4c4788fd",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/stripe-pay",
        version: "sha-ebfe5ce2a83b",
        digest: "cb2c956dd92f6c985a2c1708caca081bc41b9b82af3b1886fb9cd74ea9088e99",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/stripe-refund",
        version: "sha-48cc890c67f7",
        digest: "4f0a281e2767b666645751fe3f551731e9517a33f0bed2c68d9b91f96a8726f5",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/taste-profile",
        version: "sha-38c7de62e155",
        digest: "492ba06c3de2bee1d87a3a1886a23bb3f6d4f61c18a19fb985cbdefb25ce6e68",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/twitter",
        version: "sha-951c805a5413",
        digest: "e523410553f3a41901a30cb07eda909b7d158f25a38847bab0b83d175221208d",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/vault-unseal",
        version: "sha-5f5416092904",
        digest: "4b06413baba0efb67fa740c3367a30bc9e4a7f0a54f1b6c8d558139bf128f411",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/vuln-disclosure",
        version: "sha-b6ca0df7a27d",
        digest: "77d199cdf19017436ba4f837d11e8e595f165f3a4702f94a1f4615be2e679e7b",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/vuln-triage",
        version: "sha-0703756f489a",
        digest: "1100857cf7c0c9337e7791cbe93838789c2c7e955f50e946d0a9624cd085d327",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/weather-forecast",
        version: "sha-c270b385b135",
        digest: "b1828f4187801fe5de29c48d515ede2ffd42cab8d2ace48aab98f4aeb28cd20c",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/web-fetch",
        version: "sha-2a9765ea574f",
        digest: "89445885a1de165c3f709e00ef7e42911a8e89f048a3bd734916452dfb56720c",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/work-plan",
        version: "sha-c7b49dc5e418",
        digest: "0c4b3cbe546a009c917a9fb4b3fd380db7c147c816438f742b46b3ec3c7ae6eb",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/x402-pay",
        version: "sha-f573681a1228",
        digest: "cb3e5e85381b005a071f291ba91d822f289a9436cf6d041ad7c2a016ca8b98e9",
    },
    OfficialSkillLockEntry {
        skill_id: "runx/zapier-handoff",
        version: "sha-cb102a79ce5d",
        digest: "e2547cffb6969987bd227b3cedd05e3be3560bba44723d6cba204dd62ccb4ace",
    },
];

pub(crate) fn official_skill_entry_by_name(name: &str) -> Option<&'static OfficialSkillLockEntry> {
    let normalized = name.trim();
    OFFICIAL_SKILLS.iter().find(|entry| {
        entry.skill_id == normalized
            || entry
                .skill_id
                .strip_prefix("runx/")
                .is_some_and(|skill_name| skill_name == normalized)
    })
}
